version: "3.8"  # docker engine version

services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile.development
    environment:
      REACT_ENDPOINT: "${REACT_ENDPOINT}"
      API_ENDPOINT: "${API_ENDPOINT}"
    ports:
      - '8080:8080'